### ISSUE TITLE
https://limx.win/浏览一直提示like a robot

### ISSUE THREAD

**Issue by ntgeralt** [WingLim/frp_install_script#1]
留言提示your behavior is like a robot.
无法留言给你啦。你还可以试试nps，和frp很像，多了个web管理打开端口功能

**Comment by WingLim** [comment]
之前挂了 cloudflare 的 cdn，可能是 cloudflare 的检测问题，现在主站已经302到https://limxw.com
frp其实也有web管理端：https://github.com/fatedier/frp/blob/master/README_zh.md#admin-ui
不过这个web管理端没有你说的npx那么美观和功能没有那么完善。
